In [1]:
import os
import numpy as np
import matplotlib.pylab as plt 
import scipy.io

### 데이터 열어보기

In [2]:
mat_file = scipy.io.loadmat("/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/ADHD_part1/v1p.mat")
mat_file

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Sun Apr 12 15:32:36 2020',
 '__version__': '1.0',
 '__globals__': [],
 'v1p': array([[  85, -407,  200, ...,  -90,  473,  121],
        [-266,  -55,  -20, ..., -195,  543,   15],
        [ -90,  -19,  126, ...,  -19,  613,  261],
        ...,
        [  85,  -90,   16, ..., -512,   85,   15],
        [-160,   85, -131, ..., -477,  332,  191],
        [ 226,   85,  126, ..., -336,  297,  156]],
       shape=(12258, 19), dtype=int16)}

In [3]:
print(mat_file.keys())

dict_keys(['__header__', '__version__', '__globals__', 'v1p'])


In [5]:
data = mat_file['v1p']
print(f"원본 shape: {data.shape}")
data

원본 shape: (12258, 19)


array([[  85, -407,  200, ...,  -90,  473,  121],
       [-266,  -55,  -20, ..., -195,  543,   15],
       [ -90,  -19,  126, ...,  -19,  613,  261],
       ...,
       [  85,  -90,   16, ..., -512,   85,   15],
       [-160,   85, -131, ..., -477,  332,  191],
       [ 226,   85,  126, ..., -336,  297,  156]],
      shape=(12258, 19), dtype=int16)

In [8]:
data_T = data.T
print(f"변환 후 shape: {data_T.shape}")
data_T

변환 후 shape: (19, 12258)


array([[  85, -266,  -90, ...,   85, -160,  226],
       [-407,  -55,  -19, ...,  -90,   85,   85],
       [ 200,  -20,  126, ...,   16, -131,  126],
       ...,
       [ -90, -195,  -19, ..., -512, -477, -336],
       [ 473,  543,  613, ...,   85,  332,  297],
       [ 121,   15,  261, ...,   15,  191,  156]],
      shape=(19, 12258), dtype=int16)

### ADHD_part1

In [10]:
folder_path = "/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/ADHD_part1/"
save_folder = "/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/ADHD_part1_npy/"
os.makedirs(save_folder, exist_ok=True)

mat_files = [f for f in os.listdir(folder_path) if f.endswith('.mat')]
print(f"총 {len(mat_files)}개 파일 발견!")

총 30개 파일 발견!


In [11]:
for file_name in mat_files:
    file_path = os.path.join(folder_path, file_name)
    mat = scipy.io.loadmat(file_path)
    # key 이름 (예: 'v1p' ← 파일명에서 확장자 제거)
    key_name = os.path.splitext(file_name)[0]
    data = mat[key_name]
    data_T = data.T

    save_path = os.path.join(save_folder, key_name + ".npy")
    
    np.save(save_path, data_T)
    
    print(f"{file_name} → {key_name}.npy 저장 완료! shape: {data_T.shape}")

print(f"\n✅ 총 {len(mat_files)}개 파일 모두 .npy 파일로 저장 완료")

v36p.mat → v36p.npy 저장 완료! shape: (19, 17401)
v20p.mat → v20p.npy 저장 완료! shape: (19, 35328)
v40p.mat → v40p.npy 저장 완료! shape: (19, 20097)
v21p.mat → v21p.npy 저장 완료! shape: (19, 16574)
v6p.mat → v6p.npy 저장 완료! shape: (19, 17561)
v173.mat → v173.npy 저장 완료! shape: (19, 24241)
v37p.mat → v37p.npy 저장 완료! shape: (19, 9286)
v10p.mat → v10p.npy 저장 완료! shape: (19, 14304)
v30p.mat → v30p.npy 저장 완료! shape: (19, 21663)
v1p.mat → v1p.npy 저장 완료! shape: (19, 12258)
v27p.mat → v27p.npy 저장 완료! shape: (19, 28880)
v31p.mat → v31p.npy 저장 완료! shape: (19, 11679)
v12p.mat → v12p.npy 저장 완료! shape: (19, 17604)
v28p.mat → v28p.npy 저장 완료! shape: (19, 27612)
v24p.mat → v24p.npy 저장 완료! shape: (19, 16385)
v3p.mat → v3p.npy 저장 완료! shape: (19, 33570)
v32p.mat → v32p.npy 저장 완료! shape: (19, 18049)
v33p.mat → v33p.npy 저장 완료! shape: (19, 29217)
v25p.mat → v25p.npy 저장 완료! shape: (19, 9894)
v29p.mat → v29p.npy 저장 완료! shape: (19, 24193)
v18p.mat → v18p.npy 저장 완료! shape: (19, 25003)
v22p.mat → v22p.npy 저장 완료! shape: (19, 121

### ADHD_part2

In [12]:
folder_path = "/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/ADHD_part2/"
save_folder = "/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/ADHD_part2_npy/"
os.makedirs(save_folder, exist_ok=True)

mat_files = [f for f in os.listdir(folder_path) if f.endswith('.mat')]
print(f"총 {len(mat_files)}개 파일 발견!")

총 31개 파일 발견!


In [13]:
for file_name in mat_files:
    file_path = os.path.join(folder_path, file_name)
    mat = scipy.io.loadmat(file_path)
    # key 이름 (예: 'v1p' ← 파일명에서 확장자 제거)
    key_name = os.path.splitext(file_name)[0]
    data = mat[key_name]
    data_T = data.T

    save_path = os.path.join(save_folder, key_name + ".npy")
    
    np.save(save_path, data_T)
    
    print(f"{file_name} → {key_name}.npy 저장 완료! shape: {data_T.shape}")

print(f"\n✅ 총 {len(mat_files)}개 파일 모두 .npy 파일로 저장 완료")

v177.mat → v177.npy 저장 완료! shape: (19, 16697)
v215.mat → v215.npy 저장 완료! shape: (19, 21372)
v200.mat → v200.npy 저장 완료! shape: (19, 12739)
v213.mat → v213.npy 저장 완료! shape: (19, 12353)
v206.mat → v206.npy 저장 완료! shape: (19, 20173)
v204.mat → v204.npy 저장 완료! shape: (19, 20456)
v238.mat → v238.npy 저장 완료! shape: (19, 9852)
v198.mat → v198.npy 저장 완료! shape: (19, 19621)
v263.mat → v263.npy 저장 완료! shape: (19, 18657)
v288.mat → v288.npy 저장 완료! shape: (19, 20115)
v274.mat → v274.npy 저장 완료! shape: (19, 17323)
v270.mat → v270.npy 저장 완료! shape: (19, 23681)
v265.mat → v265.npy 저장 완료! shape: (19, 18389)
v254.mat → v254.npy 저장 완료! shape: (19, 10477)
v286.mat → v286.npy 저장 완료! shape: (19, 11465)
v279.mat → v279.npy 저장 완료! shape: (19, 20134)
v250.mat → v250.npy 저장 완료! shape: (19, 13853)
v244.mat → v244.npy 저장 완료! shape: (19, 39030)
v246.mat → v246.npy 저장 완료! shape: (19, 21307)
v284.mat → v284.npy 저장 완료! shape: (19, 15383)
v181.mat → v181.npy 저장 완료! shape: (19, 10668)
v234.mat → v234.npy 저장 완료! shape: (

### Control_part1

In [14]:
folder_path = "/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/Control_part1/"
save_folder = "/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/Control_part1_npy/"
os.makedirs(save_folder, exist_ok=True)

mat_files = [f for f in os.listdir(folder_path) if f.endswith('.mat')]
print(f"총 {len(mat_files)}개 파일 발견!")

총 30개 파일 발견!


In [15]:
for file_name in mat_files:
    file_path = os.path.join(folder_path, file_name)
    mat = scipy.io.loadmat(file_path)
    # key 이름 (예: 'v1p' ← 파일명에서 확장자 제거)
    key_name = os.path.splitext(file_name)[0]
    data = mat[key_name]
    data_T = data.T

    save_path = os.path.join(save_folder, key_name + ".npy")
    
    np.save(save_path, data_T)
    
    print(f"{file_name} → {key_name}.npy 저장 완료! shape: {data_T.shape}")

print(f"\n✅ 총 {len(mat_files)}개 파일 모두 .npy 파일로 저장 완료")

v57p.mat → v57p.npy 저장 완료! shape: (19, 14692)
v41p.mat → v41p.npy 저장 완료! shape: (19, 12500)
v56p.mat → v56p.npy 저장 완료! shape: (19, 14139)
v60p.mat → v60p.npy 저장 완료! shape: (19, 12929)
v114.mat → v114.npy 저장 완료! shape: (19, 13304)
v51p.mat → v51p.npy 저장 완료! shape: (19, 7983)
v115.mat → v115.npy 저장 완료! shape: (19, 15651)
v47p.mat → v47p.npy 저장 완료! shape: (19, 10864)
v116.mat → v116.npy 저장 완료! shape: (19, 19301)
v112.mat → v112.npy 저장 완료! shape: (19, 15943)
v107.mat → v107.npy 저장 완료! shape: (19, 19794)
v113.mat → v113.npy 저장 완료! shape: (19, 15574)
v46p.mat → v46p.npy 저장 완료! shape: (19, 9823)
v111.mat → v111.npy 저장 완료! shape: (19, 15310)
v50p.mat → v50p.npy 저장 완료! shape: (19, 16239)
v110.mat → v110.npy 저장 완료! shape: (19, 16549)
v45p.mat → v45p.npy 저장 완료! shape: (19, 10871)
v109.mat → v109.npy 저장 완료! shape: (19, 16044)
v53p.mat → v53p.npy 저장 완료! shape: (19, 19122)
v108.mat → v108.npy 저장 완료! shape: (19, 19026)
v49p.mat → v49p.npy 저장 완료! shape: (19, 16769)
v48p.mat → v48p.npy 저장 완료! shape: (1

### Control_part2

In [16]:
folder_path = "/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/Control_part2/"
save_folder = "/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/Control_part2_npy/"
os.makedirs(save_folder, exist_ok=True)

mat_files = [f for f in os.listdir(folder_path) if f.endswith('.mat')]
print(f"총 {len(mat_files)}개 파일 발견!")

총 30개 파일 발견!


In [17]:
for file_name in mat_files:
    file_path = os.path.join(folder_path, file_name)
    mat = scipy.io.loadmat(file_path)
    # key 이름 (예: 'v1p' ← 파일명에서 확장자 제거)
    key_name = os.path.splitext(file_name)[0]
    data = mat[key_name]
    data_T = data.T

    save_path = os.path.join(save_folder, key_name + ".npy")
    
    np.save(save_path, data_T)
    
    print(f"{file_name} → {key_name}.npy 저장 완료! shape: {data_T.shape}")

print(f"\n✅ 총 {len(mat_files)}개 파일 모두 .npy 파일로 저장 완료")

v149.mat → v149.npy 저장 완료! shape: (19, 17098)
v302.mat → v302.npy 저장 완료! shape: (19, 17841)
v129.mat → v129.npy 저장 완료! shape: (19, 11208)
v303.mat → v303.npy 저장 완료! shape: (19, 19222)
v117.mat → v117.npy 저장 완료! shape: (19, 25659)
v300.mat → v300.npy 저장 완료! shape: (19, 25985)
v310.mat → v310.npy 저장 완료! shape: (19, 17793)
v304.mat → v304.npy 저장 완료! shape: (19, 13400)
v305.mat → v305.npy 저장 완료! shape: (19, 22273)
v307.mat → v307.npy 저장 완료! shape: (19, 22807)
v298.mat → v298.npy 저장 완료! shape: (19, 17782)
v299.mat → v299.npy 저장 완료! shape: (19, 22260)
v138.mat → v138.npy 저장 완료! shape: (19, 12488)
v306.mat → v306.npy 저장 완료! shape: (19, 18301)
v121.mat → v121.npy 저장 완료! shape: (19, 16377)
v134.mat → v134.npy 저장 완료! shape: (19, 13359)
v120.mat → v120.npy 저장 완료! shape: (19, 12033)
v308.mat → v308.npy 저장 완료! shape: (19, 17025)
v297.mat → v297.npy 저장 완료! shape: (19, 13697)
v123.mat → v123.npy 저장 완료! shape: (19, 14550)
v309.mat → v309.npy 저장 완료! shape: (19, 24818)
v133.mat → v133.npy 저장 완료! shape: 

### npy 파일 확인

In [2]:
# npy 파일 경로 지정
file_path = "/Users/yoon-yeobin/prismlab1/ADHD/IEEE ADHD Data sets/ADHD_part1_npy/v1p.npy"

# npy 파일 불러오기
data = np.load(file_path)

# 데이터 확인
print(data.shape)  # (19, 시간)
print(data)

(19, 12258)
[[  85 -266  -90 ...   85 -160  226]
 [-407  -55  -19 ...  -90   85   85]
 [ 200  -20  126 ...   16 -131  126]
 ...
 [ -90 -195  -19 ... -512 -477 -336]
 [ 473  543  613 ...   85  332  297]
 [ 121   15  261 ...   15  191  156]]
